name: Build and Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR file with Maven
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{AWS_REGION}}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-region: ${{AWS_REGION}}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ECR_REPO}} .
          docker tag ${{ECR_REPO}}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{AWS_REGION}}.amazonaws.com/${{ECR_REPO}}:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{AWS_REGION}}.amazonaws.com/${{ECR_REPO}}:latest
